### ISSUE TITLE
There are 29 days left

### ISSUE THREAD

**Issue by Msuf123** [DakshuGill/Stone-Paper-Scissor#6]
You have to make a web app where users can login and see the orders history and buy more.
The shop keeper can login and  list their products.

**Comment by Msuf123** [comment]
28 days left

**Comment by DakshuGill** [comment]
I know that brother very well. You just focus on growing your github channel and learn angular. I know my work and will do it much better.

**Comment by Msuf123** [comment]
Bhai comedy to achi karte ho
Dekhte hai 28 days ke baad😂

**Comment by Msuf123** [comment]
26 days left

**Comment by Msuf123** [comment]
Bhai 21 din to ho hi gye ab 8 din rhe gye

**Comment by DakshuGill** [comment]
Hn bhai aacha hua aapne yadd dila diya

**Comment by Msuf123** [comment]
chal bhai is issue ko close kar rha hu m
